name: Release (Linux)

on:
  workflow_call:

jobs:
  linux:
    name: Linux (Generic)

    runs-on: ubuntu-20.04

    steps:
    - name: Download source
      uses: actions/download-artifact@v3
      with:
        name: internal-source

    - name: Unpack source
      run: |
        tar -xf source.tar.gz --strip-components=1

    - name: Install dependencies
      run: |
        echo "::group::Install system dependencies"
        # ICU is used as vcpkg fails to install ICU. Other dependencies
        # are needed either for vcpkg or for the packages installed with
        # vcpkg.
        sudo apt install -y \
          build-essential \
          ninja-build \
          libicu libicu-dev \
          fluidsynth libfluidsynth-dev \
          libasound2-dev \
          libjack-jackd2-dev \
          libpulse-dev \
          libfontconfig-dev \
          libfreetype-dev \
          liblzma-dev \
          libpng-dev \
          liblzo2-dev \
          libsdl2-dev \
          zlib1g-dev \
          python3 \
          # EOF

    - name: Install GCC problem matcher
      uses: ammaraskar/gcc-problem-matcher@master

    - name: Build
      run: |
        mkdir -p build
        cd build

        echo "::group::CMake"
        cmake ${GITHUB_WORKSPACE} \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DOPTION_PACKAGE_DEPENDENCIES=ON \
          -G Ninja \
          # EOF
        echo "::endgroup::"

        echo "::group::Build"
        echo "Building with Ninja"
        ninja
        echo "::endgroup::"

    - name: Create bundles
      run: |
        cd ${GITHUB_WORKSPACE}/build
        echo "::group::Run CPack"
        cpack
        echo "::endgroup::"

        echo "::group::Cleanup"
        # Remove the sha256 files CPack generates; we will do this ourself at
        # the end of this workflow.
        rm -f bundles/*.sha256
        echo "::endgroup::"

    - name: Store bundles
      uses: actions/upload-artifact@v3
      with:
        name: openttd-linux-generic
        path: build/bundles
        retention-days: 5
